<html>
<head>
  <title>Scraper player</title>
  <script src="player.js"></script>
  <link href="style.css" rel="stylesheet"></link>
</head>

<body>

<h1>Scraper player</h1>

<!-- <embed type="application/x-vlc-plugin"
         name="video1"
         autoplay="no" loop="yes" width="400" height="300"
         target="<?php echo $link; ?>" /> -->


  <video id="audio" preload="auto" tabindex="0" controls="" >
  <source src="">
   Your browser does not support the video tag.
  </video>

  <ul id="playlist">

  </ul>

</body>
</html>
